version: '2'
services:
  meteor:
    scale: 1
    start_on_create: false
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: meteor
        source_port: 80
        target_port: 8080
      config: |-
        global
            maxconn 4096
            maxpipes 1024
        meteor 80
            balance leastconn
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
